# Generated by Django 5.1.7 on 2025-04-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classs', models.CharField(max_length=10)),
                ('relay', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('ssrieum', models.IntegerField()),
                ('basketball', models.IntegerField()),
                ('soccer', models.IntegerField()),
                ('dodge_ball', models.IntegerField()),
                ('jump_rope', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'event',
            },
        ),
    ]
